<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_60d37206a3f7b',
        'title' => 'Header',
        'fields' => array(
            array(
                'key' => 'field_60d37797f052d',
                'label' => 'Inicia ya',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_60d372155aa3a',
                'label' => 'Boton inicia ya',
                'name' => 'button_start',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Agregar link',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60d372505aa3b',
                        'label' => 'Pais',
                        'name' => 'bs_country',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'CL' => 'Chile',
                            'CO' => 'Colombia',
                            'MX' => 'México',
                            'PE' => 'Perú',
                            'BO' => 'Bolivia',
                            'CR' => 'Costa Rica',
                            'EC' => 'Ecuador',
                            'SV' => 'El Salvador',
                            'GT' => 'Guatemala',
                            'PA' => 'Panamá',
                            'DO' => 'Dominicana',
                            'PR' => 'Puerto Rico'
                        ),
                        'default_value' => 'PE',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_60d374fe5aa3c',
                        'label' => 'Link',
                        'name' => 'bs_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '70',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'blog-header-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;